Repository HajimeKawahara/exojax, pull requests merged in 2022-01, with the labels that each got.

#195 Features/fastchem2
  examples/tutorial/Using FastChem2 to calculate the chemical abundances.ipynb
  src/exojax/atm/atmprof.py
  src/exojax/atm/fastchem2_call.py
Labels: enhancement

#197 sphinx completed
  src/exojax/atm/fastchem2_call.py
Labels: documentation

#202 Bugfix/numpyro
  documents/developers/pytest.rst
  src/exojax/spec/dit.py
  tests/dynamics/test_getE.py
  tests/reverse/README.md
  tests/reverse/reverse_lpf.py
  tests/reverse/spectrum.txt
Labels: bug
