Repository HajimeKawahara/exojax, pull requests merged in 2023-06, with the labels that each got.

#387 removed negative value assert (hotfix to v1.3)
  src/exojax/spec/set_ditgrid.py
Labels: bug

#388 Multi molecule handler
  src/exojax/spec/__init__.py
  src/exojax/spec/api.py
  src/exojax/spec/atmrt.py
  src/exojax/spec/atomllapi.py
  src/exojax/spec/contdb.py
  src/exojax/spec/multimol.py
  src/exojax/utils/mollabel.py
  src/exojax/utils/molname.py
  tests/unittests/spec/multimol/default_path_test.py
  tests/unittests/utils/mollabel_test.py
  tests/unittests/utils/molname_test.py
Labels: enhancement

#392 Unittest update
  .github/workflows/main.yml
  setup.py
  src/exojax/spec/atmrt.py
  src/exojax/spec/set_ditgrid.py
  tests/integration/unittests_long/lpf/lpf_test.py
  tests/integration/unittests_long/premodit/lbd_test.py
  tests/integration/unittests_long/premodit/lbderror_test.py
  tests/integration/unittests_long/premodit/optgrid_test.py
  tests/integration/unittests_long/premodit/premodit_spectrum_test.py
  tests/integration/unittests_long/premodit/premodit_test.py
  tests/integration/unittests_long/premodit/premodit_transmission_test.py
  tests/integration/unittests_long/premodit/premodit_xsection_test.py
  tests/unittests/atm/layer_test.py
  tests/unittests/spec/atmrt/atmrt_test.py
  tests/unittests/spec/modit/modit_spectrum_test.py
  tests/unittests/spec/transmission/transmission_pure_absorption_test.py
  tests/unittests/utils/jaxstatus_test.py
  tests/unittests/utils/memuse_test.py
Labels: bug

#393 installation doc updated
  documents/userguide/installation.rst
Labels: documentation

#394 Integration tests maintenance
  src/exojax/spec/api.py
  src/exojax/spec/moldb.py
  tests/integration/api/api_hitran_hitemp_test.py
  tests/integration/comparison/premodit/comp_lsd_test.py
  tests/integration/modit_scanfft/modit_scanfft_test.py
  tests/integration/moldb/mdbhitemp_test.py
  tests/integration/opacalc/opacalc_test.py
Labels: refactoring

#395 Wavelength order
  src/exojax/spec/opacalc.py
  src/exojax/spec/opacont.py
  src/exojax/spec/unitconvert.py
  src/exojax/test/emulate_mdb.py
  src/exojax/utils/checkarray.py
  src/exojax/utils/grids.py
  tests/endtoend/reverse/reverse_modit.py
  tests/endtoend/reverse/reverse_precompute_grid.py
  tests/endtoend/reverse/reverse_premodit.py
  tests/endtoend/reverse/reverse_premodit_blackjax.py
  tests/endtoend/reverse/reverse_premodit_transmission.py
  tests/integration/comparison/transmission/comparison_with_kawashima_transmission.py
  tests/unittests/utils/grids_test.py
Labels: refactoring

#397 uncertainties for hitran and hitemp
  src/exojax/spec/api.py
  src/exojax/spec/initspec.py
  tests/integration/api/api_hitran_hitemp_test.py
Labels: enhancement

#400 opadirect for kurucz
  src/exojax/spec/moldb.py
  src/exojax/spec/opacalc.py
  src/exojax/spec/opacont.py
  tests/endtoend/metals/Kurucz_linelist_test.py
  tests/endtoend/metals/VALD_MODIT_test.py
  tests/endtoend/metals/opacity_Fe_test.py
  tests/integration/adb/adbkurucz_test.py
Labels: enhancement

#402 OpaDirect for VALD and fix HITRAN api
  src/exojax/spec/api.py
  src/exojax/spec/moldb.py
  src/exojax/spec/opacalc.py
  tests/integration/adb/adbvald_test.py
  tests/integration/api/api_hitran_hitemp_test.py
Labels: enhancement
