Repository HajimeKawahara/exojax, pull requests merged in 2023-04, with the labels that each got.

#371 Mask for mdb class
  src/exojax/spec/api.py
Labels: enhancement

#372 Reviced api.py for non-air broadening parameter
  src/exojax/spec/api.py
Labels: enhancement

#374 Merge hitemp hitran methods
  src/exojax/spec/api.py
  tests/integration/api/api_hitran_hitemp_test.py
  tests/unittests/spec/transmission/transmission_pure_absorption_test.py
Labels: refactoring

#375 Sphinx no execute and documents edit
  README.md
  documents/userguide/api.rst
  documents/userguide/installation.rst
  documents/userguide/memorysetting.rst
  src/exojax/__init__.py
  src/exojax/test/emulate_mdb.py
  src/exojax/test/generate_methane_spectrum.py
  src/exojax/test/generate_methane_trans.py
  src/exojax/test/generate_xs.py
Labels: documentation

#370 grid broadening optimization
  documents/analysis/premodit_brodening_4per3factor.ipynb
  src/exojax/spec/initspec.py
  src/exojax/spec/opacalc.py
  src/exojax/spec/optgrid.py
  src/exojax/spec/premodit.py
  src/exojax/spec/set_ditgrid.py
  src/exojax/test/emulate_broadpar.py
  tests/unittests/spec/ditgrid/set_ditgrid_test.py
  tests/unittests/spec/premodit/optgrid_test.py
  tests/unittests/spec/premodit/premodit_test.py
Labels: bug, enhancement

#373 Removed __slots__ in MdbExomol in api.py
  documents/userguide/api.rst
  src/exojax/spec/api.py
Labels: refactoring

#377 removed failed merge part
  src/exojax/spec/api.py
Labels: bug

#379 Spectral operator
  documents/tutorials/Reverse_modeling_with_VALD_using_MODIT.ipynb
  documents/tutorials/get_started.ipynb
  documents/tutorials/get_started.rst
  src/exojax/atm/atmprof.py
  src/exojax/spec/atmrt.py
  src/exojax/spec/specop.py
  src/exojax/utils/grids.py
  tests/endtoend/jaxopt/optimize_spectrum_JAXopt_test.py
  tests/endtoend/reverse/reverse_lpf.py
  tests/unittests/atm/layer_test.py
  tests/unittests/spec/modit/modit_test.py
  tests/unittests/spec/response/response_test.py
  tests/unittests/spec/response/spin_rotation_test.py
  tests/unittests/spec/transmission/transmission_pure_absorption_test.py
Labels: enhancement, refactoring

#380 Refactoring and document update
  documents/exojax.png
  documents/tutorials/get_started.ipynb
  documents/tutorials/get_started.rst
  documents/tutorials/optimize_spectrum_JAXopt.ipynb
  documents/tutorials/optimize_spectrum_JAXopt.rst
  documents/tutorials/reverse_premodit.ipynb
  documents/tutorials/reverse_premodit.rst
  documents/userguide.rst
  src/exojax/spec/response.py
  src/exojax/spec/specop.py
  tests/endtoend/jaxopt/optimize_spectrum_JAXopt_test.py
  tests/endtoend/reverse/reverse_lpf.py
  tests/unittests/spec/response/spin_rotation_test.py
Labels: documentation, refactoring

#376 Single broadening parameter
  documents/userguide/premodit.rst
  src/exojax/spec/initspec.py
  src/exojax/spec/opacalc.py
  src/exojax/spec/premodit.py
  tests/unittests/spec/premodit/premodit_spectrum_test.py
  tests/unittests/spec/premodit/premodit_test.py
  tests/unittests/spec/premodit/premodit_xsection_test.py
Labels: enhancement

#378 Nonair CO broadening using the fitting formula
  documents/userguide.rst
  documents/userguide/api.rst
  documents/userguide/nonair.rst
  src/exojax/spec/api.py
  src/exojax/spec/nonair.py
  src/exojax/spec/qstate.py
  tests/integration/comparison/nonair/nonair_co_hitran_comp.py
  tests/integration/moldb/nonair_co_hitemp.py
  tests/unittests/spec/nonair/nonair_test.py
  tests/unittests/spec/qstate/qstate_test.py
Labels: experimental
