Repository HajimeKawahara/exojax, pull requests merged in 2024-01, with the labels that each got.

#450 Fitting the telluric model to WASP33b HDS data
  documents/tutorials.rst
  documents/tutorials/Comparing_HITEMP_and_ExoMol.rst
  documents/tutorials/Fitting_Telluric_Lines.ipynb
  documents/tutorials/jupyter2rst_each.py
  documents/tutorials/list.dat
  src/exojax/spec/unitconvert.py
  src/exojax/utils/checkarray.py
  tests/unittests/utils/unitconvert_test.py
Labels: documentation

#451 Raise error when none of the lines in opa.mdb are within opa.nu_grid for opa=OpaPremodit
  src/exojax/spec/opacalc.py
  src/exojax/utils/checkarray.py
  tests/integration/api/inconsistent_nu_error_test.py
  tests/unittests/utils/grids_test.py
Labels: enhancement

#454 optelower for HITEMP
  src/exojax/spec/optgrid.py
  tests/integration/unittests_long/premodit/optgrid_test.py
Labels: bug

#455 bug when the elower_max option is given in MdbHitemp
  src/exojax/spec/api.py
  tests/integration/api/hitemp_elowermax_test.py
Labels: bug

#459 added warning and exit statement in MultiMol
  src/exojax/spec/multimol.py
Labels: enhancement

#461 added allow_32bit option for MultiMol.multiopa_premodit
  src/exojax/spec/multimol.py
Labels: bug

#460 Just modified scripts for the comparison with petitRADTRANS to include intensity-based calculations
  tests/integration/comparison/twostream/comparison_petitRADTRANS_CIA.py
  tests/integration/comparison/twostream/comparison_petitRADTRANS_narrow_R70000.py
  tests/integration/comparison/twostream/comparison_petitRADTRANS_wide_R7000.py
  tests/integration/comparison/twostream/output/CIA_R70000.png
Labels: comparison

#464 Fix opachord.py to avoid nan in the gradient of ArtTransPure model
  src/exojax/spec/opachord.py
  tests/integration/unittests_long/transmission/transmission_grad.py
Labels: bug

#465 Refactoring transmission related codes
  src/exojax/atm/atmprof.py
  src/exojax/spec/atmrt.py
  src/exojax/spec/opachord.py
  tests/integration/unittests_long/transmission/transmission_grad.py
  tests/integration/unittests_long/transmission/transmission_grad_test.py
Labels: refactoring

#467 Refact2
  src/exojax/spec/api.py
Labels: refactoring

#469 Doc2024 1
  documents/developers/doc.rst
  documents/developers/pytest.rst
  documents/index.rst
  documents/tutorials.rst
  documents/tutorials/Ackerman_and_Marley_cloud_model.ipynb
  documents/tutorials/Ackerman_and_Marley_cloud_model.rst
  documents/tutorials/Comparing_HITEMP_and_ExoMol.ipynb
  documents/tutorials/Comparing_HITEMP_and_ExoMol.rst
  documents/tutorials/Fitting_Telluric_Lines.ipynb
  documents/tutorials/Fortrat.rst
  documents/tutorials/Rigid_Rotation.ipynb
  documents/tutorials/Rigid_Rotation.rst
  documents/tutorials/Transmission_beta.ipynb
  documents/tutorials/Transmission_beta.rst
  documents/tutorials/Transmission_beta_files/Transmission_beta_10_4.png
  documents/tutorials/get_started.ipynb
  documents/tutorials/get_started.rst
  documents/tutorials/hjerting.ipynb
  documents/tutorials/hjerting.rst
  documents/tutorials/list.dat
  documents/tutorials/opacity.ipynb
  documents/tutorials/opacity_exomol.rst
  documents/tutorials/optimize_spectrum.ipynb
  documents/tutorials/optimize_spectrum_JAXopt.ipynb
  documents/tutorials/optimize_spectrum_JAXopt.rst
  documents/tutorials/optimize_voigt.ipynb
  documents/tutorials/optimize_voigt.rst
  documents/tutorials/optimize_voigt_JAXopt.ipynb
  documents/tutorials/reverse_precompute_grid.ipynb
  documents/tutorials/reverse_precompute_grid.rst
  documents/tutorials/reverse_premodit.ipynb
  documents/tutorials/reverse_premodit.rst
  documents/userguide/atomll.rst
  documents/userguide/mdb.rst
  documents/userguide/opacalc.rst
  documents/userguide/premodit.rst
  documents/userguide/rtransfer.rst
  documents/userguide/rtransfer_ibased_pure.rst
  documents/userguide/rtransfer_transmission.rst
  documents/userguide/sop.rst
Labels: documentation

#470 added figures
  documents/exojax.png
  documents/rt.png
  documents/tutorials/get_started.ipynb
  documents/tutorials/get_started.rst
  documents/userguide/rtransfer.rst
Labels: documentation

#471 Readme update
  README.md
Labels: documentation
