Repository HajimeKawahara/exojax, pull requests merged in 2024-08, with the labels that each got.

#499 Correct Q(T) to Q(T)/Q(Tref)
  documents/tutorials/Forward_modeling_for_Fe_I_lines_of_Kurucz.ipynb
  documents/tutorials/Forward_modeling_for_metal_line.ipynb
  src/exojax/spec/atomll.py
  src/exojax/spec/atomllapi.py
  src/exojax/spec/lpf.py
  src/exojax/spec/modit.py
  src/exojax/spec/moldb.py
  src/exojax/spec/opacalc.py
  tests/endtoend/metals/opacity_Fe_test.py
Labels: bug

#501 Refactoring: removes recexomol.py
  requirements.txt
  src/exojax/utils/recexomol.py
  tests/unittests/utils/recexomol_test.py
Labels: refactoring

#500 Matches the installation requirements for radis 0.15
  .github/workflows/main.yml
  requirements.txt
  setup.py
  src/exojax/spec/api.py
  src/exojax/spec/atomllapi.py
  src/exojax/spec/moldb.py
  tests/unittests/install/func.py
Labels: common API compatibility

#506 api.py for pytables
  documents/userguide/api.rst
  setup.py
  src/exojax/spec/api.py
  tests/integration/api/api_pytables_test.py
  tests/integration/api/download_h2s.py
Labels: bug, common API compatibility

#507 doc update completed
  documents/tutorials/Transmission_beta.rst
  documents/userguide/api.rst
  documents/userguide/installation.rst
Labels: documentation

#508 Doc2408
  README.md
  documents/index.rst
  documents/userguide/api.rst
  documents/userguide/history.rst
  documents/userguide/mie.rst
  documents/userguide/pdb.rst
Labels: documentation

#512 eq (==) and neq (!=) methods are defined in mdb and opa
  src/exojax/spec/api.py
  src/exojax/spec/moldb.py
  src/exojax/spec/opacalc.py
  src/exojax/test/generate_xs.py
  tests/endtoend/metals/Kurucz_linelist_test.py
  tests/endtoend/reverse/reverse_lpf.py
  tests/integration/api/api_premodit_to_direct.py
  tests/integration/comparison/premodit/fig_tablexs_error.py
  tests/integration/opacalc/opacalc_test.py
  tests/integration/unittests_long/lpf/lpf_test.py
  tests/unittests/spec/api/api_eq_method_test.py
  tests/unittests/spec/opa/opadirect_call_test.py
  tests/unittests/spec/opa/opadirect_eq_test.py
  tests/unittests/spec/opa/opamodit_call_test.py
  tests/unittests/spec/opa/opamodit_eq_test.py
  tests/unittests/spec/opa/opapremodit_call_test.py
  tests/unittests/spec/opa/opapremodit_eq_test.py
Labels: enhancement

#514 unit test to check line strengths
  tests/unittests/spec/api/api_line_strength_test.py
Labels: enhancement

#515 No change mdb (Exomol, HITRAN, Hitemp) from opa
  src/exojax/spec/api.py
  src/exojax/spec/modit.py
  src/exojax/spec/opacalc.py
  src/exojax/test/generate_xs.py
  tests/integration/api/api_premodit_to_direct.py
  tests/integration/moldb/quantum_states_filter_exomol.py
  tests/integration/moldb/quantum_states_filter_hitemp.py
  tests/integration/moldb/quantum_states_filter_hitran_co.py
  tests/integration/premodit/checkindex.py
  tests/unittests/spec/api/api_eq_method_test.py
  tests/unittests/spec/api/api_line_strength_test.py
  tests/unittests/spec/modit/modit_test.py
  tests/unittests/spec/opa/opamodit_call_test.py
  tests/unittests/spec/opa/sideeffect_test.py
Labels: enhancement

#516 v1 -> v2
  .github/workflows/main.yml
Labels: maintenance

#517 Refac ola2experimetal
  src/exojax/experimental/__init__.py
  src/exojax/experimental/presolar.py
  src/exojax/experimental/shapefilter.py
  tests/unittests/experimental/presolar/presolar_test.py
  tests/unittests/experimental/presolar/shapefilter_test.py
  tests/unittests/spec/presolar/presolar_xsection_test.py
Labels: refactoring, maintenance

#518 Reflection Spectrum in Practice
  README.md
  documents/tutorials/Ackerman_and_Marley_cloud_model.ipynb
  documents/tutorials/Jupiter_Hires_Modeling_NIR_fitting_clouds.py
  documents/tutorials/Jupiter_cloud_model_using_amp_debug.py
  documents/tutorials/jupiter_corrected.dat
  documents/tutorials/jupiters/Jupiter_Hires_Modeling.ipynb
  documents/tutorials/jupiters/Jupiter_Hires_Modeling_Exomol.ipynb
  documents/tutorials/jupiters/Jupiter_Hires_Modeling_NIR.ipynb
  documents/tutorials/jupiters/Jupiter_Hires_Modeling_NIR_fitting.ipynb
  documents/tutorials/jupiters/Jupiter_Hires_Modeling_NIR_fitting_clouds.py
  documents/tutorials/jupiters/Jupiter_cloud_model.ipynb
  documents/tutorials/jupiters/Jupiter_cloud_model_using_amp.ipynb
  documents/tutorials/jupiters/miegrid_generate.py
  documents/tutorials/jupiters/plotjupiter.py
  src/exojax/__init__.py
  src/exojax/atm/amclouds.py
  src/exojax/atm/atmphys.py
  src/exojax/spec/atmrt.py
  src/exojax/spec/dit.py
  src/exojax/spec/hitrancia.py
  src/exojax/spec/mie.py
  src/exojax/spec/opacont.py
  src/exojax/spec/pardb.py
  src/exojax/spec/rtransfer.py
  src/exojax/spec/toon.py
  src/exojax/spec/twostream.py
  tests/unittests/atm/cloud_base_test.py
  tests/unittests/atm/smooth_index_test.py
Labels: enhancement
