Repository HajimeKawahara/exojax, pull requests merged in 2024-02, with the labels that each got.

#472 added nstream=2 just in case in the test scripts for the comparison with petitRADTRANS
  tests/integration/comparison/twostream/comparison_petitRADTRANS_CIA.py
  tests/integration/comparison/twostream/comparison_petitRADTRANS_narrow_R70000.py
  tests/integration/comparison/twostream/comparison_petitRADTRANS_wide_R7000.py
Labels: Examples/Tutorials

#476 jnp.trapz is deprecated. Replaced it to jax.scipy.integrate.trapezoid
  src/exojax/spec/rtransfer.py
Labels: maintenance

#475 potential solution that reduces divergences in fbased rt
  src/exojax/spec/rtransfer.py
Labels: enhancement
