Repository HajimeKawahara/exojax, pull requests merged in 2025-05, with the labels that each got.

#598 Set custom JVP for sqrt in opachord to enable forward mode differentiation of transmission
  requirements.txt
  src/exojax/spec/opachord.py
Labels: bug

#600 Exomolhr
  MANIFEST.in
  documents/tutorials/exomolhr.ipynb
  documents/tutorials/exomolhr.rst
  documents/tutorials/exomolhr_files/exomolhr_11_1.png
  documents/userguide.rst
  examples/spec_with_photo.py
  src/exojax/data/testdata/20250503072507__1H2-16O__296.0K.csv
  src/exojax/spec/api.py
  src/exojax/spec/exomolhr.py
  src/exojax/test/data.py
  src/exojax/utils/url.py
  tests/endtoend/identify_lines/lines_exomolhr.py
  tests/integration/exomolhr_check/exomolhr_online_test.py
  tests/unittests/spec/exomolhr/exomolhr_test.py
Labels: enhancement

#601 updates docs for xdb and doc
  documents/developers/doc.rst
  documents/tutorials.rst
  documents/userguide.rst
  documents/userguide/xdb.rst
Labels: documentation

#602 added DeepWiki batch and links in README.md and top page of docs
  README.md
  documents/index.rst
Labels: documentation

#605 Documentation update
  MANIFEST.in
  README.md
  documents/index.rst
  documents/userguide.rst
  documents/userguide/customapi.rst
  documents/userguide/customapi_files/customapi_13_18.png
  documents/userguide/customapi_files/customapi_13_19.png
  documents/userguide/customapi_files/customapi_13_20.png
  documents/userguide/customapi_files/customapi_16_0.png
Labels: documentation
